### ISSUE TITLE
Its not working for Compact Prompt Layout of A1111

### ISSUE THREAD

**Issue by FutonGama** [CurtisDS/extra-network-side-panel-for-a1111#2]
![image](https://github.com/user-attachments/assets/158a124e-d746-4890-b839-1d2e428327fd)
Textual Inversion Panel: (The prompt shows on right)
![image](https://github.com/user-attachments/assets/9493ef3a-59af-4210-bc2d-5f95db99f03c)
Lora Panel: (The positive prompt shows on right and negative prompt on left)
![image](https://github.com/user-attachments/assets/22d02e44-3a27-4f09-83ac-eddb6edd8997)
Checkpoint Panel: (Checkpoint Panel seems correctly)
![image](https://github.com/user-attachments/assets/a1cffc87-f67d-400c-9a67-8fe4f2629123)

Its not working for Compact Prompt Layout of A1111

Excellent extension btw i was waiting for a extension like this for a long time, i will be very thankful if you adapt to Compact Prompt Layout. When you turn it on the prompt box and negative prompt moves the location for the wrong side.

Edit: i think this can be because of how the A1111 Extra Networks tab works with Compact Prompt Layout, they move the prompt when you click on Lora. I'm not sure now if you guys can do something on this, i hope so.

**Comment by CurtisDS** [comment]
Thats how the compact UI works. It assumes you cant see the generation settings anymore and so it moves the prompt boxes over to the extra network tabs.

I think I can fix it so that it doesnt do that when the side panel is open though. I'll post a fix in a second.

**Comment by CurtisDS** [comment]
fixed with 5119eedff482adf639de77272c6326ca5f912dab
